// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nxgbzzbwuewhpsplctxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im54Z2J6emJ3dWV3aHBzcGxjdHhkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5ODEzODAsImV4cCI6MjA3MTU1NzM4MH0.NOwehNFQN0i19WKvteZESYFraXcpQlD9AtOcP7xT9aw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});